#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file_name>"
    exit 1
fi

file_name="$1"
output_path="./code"

# Check if the code executable exists and remove it if it does
if [ -e "$output_path" ]; then
    rm "$output_path"
fi

# Compile the code
clang++ "$file_name" -o "$output_path"

# Check if compilation was successful
if [ $? -eq 0 ]; then
    # Execute the compiled code
    "$output_path"
else
    echo "Compilation failed."
fi