# https://github.com/alacritty/alacritty/tree/master#configuration

[window]

opacity = 0.5
blur = true

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant ="Dark"  # "Light" 

[font]
size = 10.0
normal = { family = "FiraCodeNerdfont", style = "Medium" }
